/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tugas8.oop;

import javax.swing.*;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author lasmanaadit
 */
public class Guipelanggan extends javax.swing.JFrame {
     private DefaultTableModel tableModel;
     private Harga harga;   

    /**
     * Creates new form Guipelanggan
     */
    public Guipelanggan() {
         initComponents();
          harga = new HargaMenu();
         tableModel = (DefaultTableModel) tbl_pelanggan.getModel();
         tableModel.setRowCount(0);
    }
private int getHargaMenu(String menu) {
    return harga.getHarga(menu);
}
    private void cetakHargaMieAyam() {
        if (harga instanceof HargaMenu) {
            HargaMenu hMenu = (HargaMenu) harga; // Downcasting
            int hargaMie = hMenu.getHarga("mie ayam");
            JOptionPane.showMessageDialog(this, "Harga Mie Ayam adalah Rp " + hargaMie);
        }
    }

 
 private void hitungTotalHarga() {
    DefaultTableModel model = (DefaultTableModel) tbl_pelanggan.getModel();
    int total = 0;

    // Loop melalui semua baris tabel untuk menghitung total harga
    for (int i = 0; i < model.getRowCount(); i++) {
        int harga = (int) model.getValueAt(i, 3); // Mengambil harga dari kolom ke-4 (index 3)
        total += harga; // Menjumlahkan harga
    }

    // Menampilkan total di txt_total
    txt_total.setText(String.valueOf(total));
}
 
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        close2 = new javax.swing.JButton();
        smpn2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        btl2 = new javax.swing.JButton();
        txt_menu = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        hps2 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_pelanggan = new javax.swing.JTable();
        cmb_kategori = new javax.swing.JComboBox();
        jLabel3 = new javax.swing.JLabel();
        txt_total = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        btn_total = new javax.swing.JButton();
        txt_jumlah = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txt_nama = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        close2.setText("Close");
        close2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                close2ActionPerformed(evt);
            }
        });

        smpn2.setText("Simpan");
        smpn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                smpn2ActionPerformed(evt);
            }
        });

        jLabel1.setText("Nama");

        btl2.setText("Batal");
        btl2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btl2ActionPerformed(evt);
            }
        });

        jLabel2.setText("Menu");

        hps2.setText("Hapus");
        hps2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hps2ActionPerformed(evt);
            }
        });

        tbl_pelanggan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "nama", "Nama Menu", "Kategori", "harga", "Jumlah"
            }
        ));
        jScrollPane1.setViewportView(tbl_pelanggan);

        cmb_kategori.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Makanan", "Snack", "Minuman" }));

        jLabel3.setText("Kategori");

        txt_total.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_totalActionPerformed(evt);
            }
        });

        jLabel4.setText("Total");

        btn_total.setText("Total");
        btn_total.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_totalActionPerformed(evt);
            }
        });

        txt_jumlah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_jumlahActionPerformed(evt);
            }
        });

        jLabel5.setText("Jumlah pesanan");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(77, 77, 77)
                        .addComponent(txt_nama, javax.swing.GroupLayout.DEFAULT_SIZE, 168, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btn_total)
                            .addComponent(txt_total)
                            .addComponent(cmb_kategori, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txt_menu, javax.swing.GroupLayout.DEFAULT_SIZE, 168, Short.MAX_VALUE)
                            .addComponent(txt_jumlah))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(smpn2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(hps2)
                        .addGap(18, 18, 18)
                        .addComponent(btl2)
                        .addGap(18, 18, 18)
                        .addComponent(close2))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 348, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(45, 45, 45))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(smpn2)
                            .addComponent(hps2)
                            .addComponent(btl2)
                            .addComponent(close2)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(txt_nama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txt_menu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(31, 31, 31)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cmb_kategori, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt_jumlah, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 19, Short.MAX_VALUE)
                .addComponent(btn_total)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_total, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(45, 45, 45))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void hps2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hps2ActionPerformed
        // TODO add your handling code here:
        int selectedRow = tbl_pelanggan.getSelectedRow();
        if (selectedRow >= 0) {
            tableModel.removeRow(selectedRow);
        } else {
            JOptionPane.showMessageDialog(this, "Pilih dulu data yang mau dihapus!");
        }
    }//GEN-LAST:event_hps2ActionPerformed

    private void btl2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btl2ActionPerformed
        // TODO add your handling code here:
        txt_nama.setText("");
        txt_menu.setText("");
        cmb_kategori.setSelectedIndex(0);
        txt_nama.requestFocus();
    }//GEN-LAST:event_btl2ActionPerformed

    private void close2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_close2ActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_close2ActionPerformed

    private void smpn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_smpn2ActionPerformed
        // TODO add your handling code here:
    String namaPelanggan = txt_nama.getText();
    String menuPelanggan = txt_menu.getText();
    String kategoriMenu = cmb_kategori.getSelectedItem().toString();

    // Coba parsing jumlah makanan dari text field baru
    int jumlah;
    try {
        jumlah = Integer.parseInt(txt_jumlah.getText());
    } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(this, "Harus memasukkan angka untuk jumlah!");
        return; // Stop eksekusi lanjut
    }

    int hargaPerItem = getHargaMenu(menuPelanggan); // Ambil harga satuan
    int totalHarga = hargaPerItem * jumlah;

    if (namaPelanggan.isEmpty() || menuPelanggan.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Nama pelanggan dan menu harus diisi!");
    } else if (hargaPerItem == 0) {
        JOptionPane.showMessageDialog(this, "Menu tidak dikenali!");
    } else {
        DefaultTableModel model = (DefaultTableModel) tbl_pelanggan.getModel();
        model.addRow(new Object[]{namaPelanggan, menuPelanggan, kategoriMenu, totalHarga, jumlah});

        txt_nama.setText("");
        txt_menu.setText("");
        txt_jumlah.setText(""); // Kosongkan jumlah
        cmb_kategori.setSelectedIndex(0);
        txt_nama.requestFocus();
    }
    }//GEN-LAST:event_smpn2ActionPerformed

    private void txt_totalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_totalActionPerformed


    }//GEN-LAST:event_txt_totalActionPerformed

    private void btn_totalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_totalActionPerformed
        // TODO add your handling code here:
        btn_total.addActionListener(new java.awt.event.ActionListener() {
    public void actionPerformed(java.awt.event.ActionEvent evt) {
        hitungTotalHarga(); // Memanggil metode hitungTotalHarga() untuk menghitung total
    }
});
    }//GEN-LAST:event_btn_totalActionPerformed

    private void txt_jumlahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_jumlahActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_jumlahActionPerformed
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Guipelanggan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Guipelanggan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Guipelanggan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Guipelanggan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Guipelanggan().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btl2;
    private javax.swing.JButton btn_total;
    private javax.swing.JButton close2;
    private javax.swing.JComboBox cmb_kategori;
    private javax.swing.JButton hps2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton smpn2;
    private javax.swing.JTable tbl_pelanggan;
    private javax.swing.JTextField txt_jumlah;
    private javax.swing.JTextField txt_menu;
    private javax.swing.JTextField txt_nama;
    private javax.swing.JTextField txt_total;
    // End of variables declaration//GEN-END:variables
}
